
#line 1 "parser/machine.rl"
// compile-command: "ragel -Z -G2 machine.rl"

/* C port of the Ragel lexer (ported from legacy Go). This file is pure C and
   uses the helpers declared in parser/lexer.h. */

#include <stdlib.h>
#include <string.h>
#include "lexer.h"
#include "tokens.h"

#define maxstack 64


#line 102 "parser/machine.rl"



#line 16 "parser/machine.c"
static const int expr_start = 22;
static const int expr_first_final = 22;
static const int expr_error = 0;

static const int expr_en_qstring = 79;
static const int expr_en_istring = 82;
static const int expr_en_expr = 22;


#line 105 "parser/machine.rl"

/* C lexical wrapper generated by Ragel */

int lexData(const char *data, int len, LexResult *r) {
    int cs = 0, act = 0;
    const char *p = data;
    const char *pe = data + len;
    const char *eof = pe;
    const char *ts = NULL, *te = NULL;
    int top = 0;
    int stack[maxstack];
    Backrefs backrefs = { NULL, 0, 0 };

    /* helper to set an error message (allocated) */
    void set_err(const char *msg) {
        if (r->errmsg) { free(r->errmsg); r->errmsg = NULL; }
        size_t m = strlen(msg) + 1;
        r->errmsg = malloc(m);
        if (r->errmsg) memcpy(r->errmsg, msg, m);
    }

    /* nostack check used by actions; returns 1 on error (and sets r->errmsg) */
    #define nostack() ( (top) >= maxstack ? (set_err("exceeds recursion limit"), 1) : 0 )

    /* append or set r->data */
    if (r->data == NULL) {
        r->data = malloc(len);
        if (!r->data) { set_err("out of memory"); return 1; }
        memcpy(r->data, data, len);
        r->len = len;
    } else {
        char *nd = realloc(r->data, r->len + len);
        if (!nd) { set_err("out of memory"); return 1; }
        r->data = nd;
        memcpy(r->data + r->len, data, len);
        r->len += len;
    }


#line 62 "parser/machine.c"
	{
	cs = expr_start;
	top = 0;
	ts = 0;
	te = 0;
	act = 0;
	}

#line 144 "parser/machine.rl"
    (void)expr_first_final; (void)expr_error; (void)expr_en_qstring; (void)expr_en_istring; (void)expr_en_expr;

    /* Ragel exec block will use the macros (tok, tokenter, tokleave, tokarg, add_lines, add_line)
       declared in parser/lexer.h and expect local variables ts, te, top, backrefs, data, p, pe, cs. */



#line 75 "parser/machine.c"
	{
	if ( p == pe )
		goto _test_eof;
	goto _resume;

_again:
	switch ( cs ) {
		case 22: goto st22;
		case 23: goto st23;
		case 1: goto st1;
		case 24: goto st24;
		case 2: goto st2;
		case 3: goto st3;
		case 25: goto st25;
		case 26: goto st26;
		case 27: goto st27;
		case 28: goto st28;
		case 29: goto st29;
		case 30: goto st30;
		case 31: goto st31;
		case 32: goto st32;
		case 33: goto st33;
		case 4: goto st4;
		case 5: goto st5;
		case 34: goto st34;
		case 35: goto st35;
		case 36: goto st36;
		case 37: goto st37;
		case 6: goto st6;
		case 38: goto st38;
		case 7: goto st7;
		case 8: goto st8;
		case 39: goto st39;
		case 40: goto st40;
		case 9: goto st9;
		case 10: goto st10;
		case 41: goto st41;
		case 42: goto st42;
		case 43: goto st43;
		case 44: goto st44;
		case 45: goto st45;
		case 11: goto st11;
		case 12: goto st12;
		case 46: goto st46;
		case 47: goto st47;
		case 48: goto st48;
		case 13: goto st13;
		case 14: goto st14;
		case 49: goto st49;
		case 50: goto st50;
		case 51: goto st51;
		case 52: goto st52;
		case 53: goto st53;
		case 54: goto st54;
		case 55: goto st55;
		case 56: goto st56;
		case 57: goto st57;
		case 58: goto st58;
		case 59: goto st59;
		case 60: goto st60;
		case 61: goto st61;
		case 62: goto st62;
		case 63: goto st63;
		case 64: goto st64;
		case 65: goto st65;
		case 66: goto st66;
		case 67: goto st67;
		case 68: goto st68;
		case 69: goto st69;
		case 70: goto st70;
		case 71: goto st71;
		case 72: goto st72;
		case 73: goto st73;
		case 74: goto st74;
		case 75: goto st75;
		case 76: goto st76;
		case 15: goto st15;
		case 77: goto st77;
		case 78: goto st78;
		case 79: goto st79;
		case 80: goto st80;
		case 16: goto st16;
		case 17: goto st17;
		case 81: goto st81;
		case 82: goto st82;
		case 83: goto st83;
		case 18: goto st18;
		case 19: goto st19;
		case 20: goto st20;
		case 21: goto st21;
		case 84: goto st84;
		case 85: goto st85;
		case 86: goto st86;
		case 0: goto st0;
	default: break;
	}

	if ( ++p == pe )
		goto _test_eof;
_resume:
	switch ( cs )
	{
tr0:
#line 98 "parser/machine.rl"
	{{p = ((te))-1;}{ tok((int)(*ts), r); }}
	goto st22;
tr2:
#line 72 "parser/machine.rl"
	{{p = ((te))-1;}{ tok(FLOAT, r); }}
	goto st22;
tr5:
#line 1 "NONE"
	{	switch( act ) {
	case 9:
	{{p = ((te))-1;} tok(ASSERT_, r); }
	break;
	case 10:
	{{p = ((te))-1;} tok(ELSE_, r); }
	break;
	case 11:
	{{p = ((te))-1;} tok(IF_, r); }
	break;
	case 12:
	{{p = ((te))-1;} tok(IN, r); }
	break;
	case 13:
	{{p = ((te))-1;} tok(INHERIT, r); }
	break;
	case 14:
	{{p = ((te))-1;} tok(LET, r); }
	break;
	case 15:
	{{p = ((te))-1;} tok(OR_, r); }
	break;
	case 16:
	{{p = ((te))-1;} tok(REC, r); }
	break;
	case 17:
	{{p = ((te))-1;} tok(THEN, r); }
	break;
	case 18:
	{{p = ((te))-1;} tok(WITH, r); }
	break;
	case 27:
	{{p = ((te))-1;} tok(FLOAT, r); }
	break;
	case 28:
	{{p = ((te))-1;} tok(INT_, r); }
	break;
	case 29:
	{{p = ((te))-1;} tok(ID, r); }
	break;
	case 30:
	{{p = ((te))-1;} tok(ELLIPSIS, r); }
	break;
	case 39:
	{{p = ((te))-1;} tok(CONCAT, r); }
	break;
	case 48:
	{{p = ((te))-1;} tok((int)(*ts), r); }
	break;
	}
	}
	goto st22;
tr14:
#line 67 "parser/machine.rl"
	{te = p+1;{ tokcomment(COMMENT, r); add_lines(r, ts, te); }}
	goto st22;
tr17:
#line 71 "parser/machine.rl"
	{te = p+1;{ tok(PATH, r); }}
	goto st22;
tr30:
#line 98 "parser/machine.rl"
	{te = p+1;{ tok((int)(*ts), r); }}
	goto st22;
tr33:
#line 65 "parser/machine.rl"
	{te = p+1;{ add_line(r, ts); }}
	goto st22;
tr35:
#line 87 "parser/machine.rl"
	{te = p+1;{ tokenter('"', '"', r); { /* replaced nostack-return to return non-zero error */ {stack[top++] = 22;goto st79;}} }}
	goto st22;
tr40:
#line 91 "parser/machine.rl"
	{te = p+1;{ tokenter('(', ')', r); { /* replaced nostack-return to return non-zero error */ {stack[top++] = 22;goto st22;}} }}
	goto st22;
tr41:
#line 94 "parser/machine.rl"
	{te = p+1;{ if (!tokleave((int)(*ts), r)) return 1; {cs = stack[--top];goto _again;} }}
	goto st22;
tr48:
#line 96 "parser/machine.rl"
	{te = p+1;{ if (!tokarg(r)) return 1; }}
	goto st22;
tr53:
#line 92 "parser/machine.rl"
	{te = p+1;{ tokenter('[', ']', r); { /* replaced nostack-return to return non-zero error */ {stack[top++] = 22;goto st22;}} }}
	goto st22;
tr63:
#line 93 "parser/machine.rl"
	{te = p+1;{ tokenter('{', '}', r); { /* replaced nostack-return to return non-zero error */ {stack[top++] = 22;goto st22;}} }}
	goto st22;
tr66:
#line 98 "parser/machine.rl"
	{te = p;p--;{ tok((int)(*ts), r); }}
	goto st22;
tr68:
#line 72 "parser/machine.rl"
	{te = p;p--;{ tok(FLOAT, r); }}
	goto st22;
tr70:
#line 64 "parser/machine.rl"
	{te = p;p--;}
	goto st22;
tr71:
#line 81 "parser/machine.rl"
	{te = p+1;{ tok(NEQ, r); }}
	goto st22;
tr72:
#line 66 "parser/machine.rl"
	{te = p;p--;{ tokcomment(COMMENT, r); }}
	goto st22;
tr73:
#line 90 "parser/machine.rl"
	{te = p+1;{ tokenter(INTERP, '}', r); { /* replaced nostack-return to return non-zero error */ {stack[top++] = 22;goto st22;}} }}
	goto st22;
tr74:
#line 79 "parser/machine.rl"
	{te = p+1;{ tok(AND, r); }}
	goto st22;
tr75:
#line 88 "parser/machine.rl"
	{te = p+1;{ tokenter(II, II, r); { /* replaced nostack-return to return non-zero error */ {stack[top++] = 22;goto st82;}}  }}
	goto st22;
tr77:
#line 69 "parser/machine.rl"
	{te = p;p--;{ tok(PATH, r); }}
	goto st22;
tr79:
#line 77 "parser/machine.rl"
	{te = p+1;{ tok(IMPL, r); }}
	goto st22;
tr83:
#line 84 "parser/machine.rl"
	{te = p+1;{ tok(UPDATE, r); }}
	goto st22;
tr84:
#line 73 "parser/machine.rl"
	{te = p;p--;{ tok(INT_, r); }}
	goto st22;
tr86:
#line 74 "parser/machine.rl"
	{te = p;p--;{ tok(ID, r); }}
	goto st22;
tr87:
#line 82 "parser/machine.rl"
	{te = p+1;{ tok(LEQ, r); }}
	goto st22;
tr88:
#line 80 "parser/machine.rl"
	{te = p+1;{ tok(EQ, r); }}
	goto st22;
tr89:
#line 83 "parser/machine.rl"
	{te = p+1;{ tok(GEQ, r); }}
	goto st22;
tr90:
#line 68 "parser/machine.rl"
	{te = p;p--;{ tok(URI, r); }}
	goto st22;
tr101:
#line 56 "parser/machine.rl"
	{te = p;p--;{ tok(IN, r); }}
	goto st22;
tr118:
#line 78 "parser/machine.rl"
	{te = p+1;{ tok(OR, r); }}
	goto st22;
tr120:
#line 70 "parser/machine.rl"
	{te = p;p--;{ tok(PATH, r); }}
	goto st22;
st22:
#line 1 "NONE"
	{ts = 0;}
	if ( ++p == pe )
		goto _test_eof22;
case 22:
#line 1 "NONE"
	{ts = p;}
#line 332 "parser/machine.c"
	switch( (*p) ) {
		case 0: goto tr31;
		case 9: goto st26;
		case 10: goto tr33;
		case 13: goto st26;
		case 32: goto st26;
		case 33: goto st27;
		case 34: goto tr35;
		case 35: goto st28;
		case 36: goto st29;
		case 38: goto st30;
		case 39: goto st31;
		case 40: goto tr40;
		case 41: goto tr41;
		case 43: goto tr42;
		case 45: goto tr43;
		case 46: goto tr44;
		case 47: goto tr45;
		case 48: goto tr46;
		case 58: goto tr48;
		case 60: goto tr49;
		case 61: goto st46;
		case 62: goto st47;
		case 64: goto tr48;
		case 91: goto tr53;
		case 93: goto tr41;
		case 95: goto tr54;
		case 97: goto tr55;
		case 101: goto tr56;
		case 105: goto tr57;
		case 108: goto tr58;
		case 111: goto tr59;
		case 114: goto tr60;
		case 116: goto tr61;
		case 119: goto tr62;
		case 123: goto tr63;
		case 124: goto st75;
		case 125: goto tr41;
		case 126: goto tr65;
	}
	if ( (*p) < 65 ) {
		if ( 49 <= (*p) && (*p) <= 57 )
			goto tr47;
	} else if ( (*p) > 90 ) {
		if ( 98 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr30;
tr31:
#line 1 "NONE"
	{te = p+1;}
	goto st23;
st23:
	if ( ++p == pe )
		goto _test_eof23;
case 23:
#line 388 "parser/machine.c"
	if ( (*p) == 46 )
		goto st1;
	goto tr66;
st1:
	if ( ++p == pe )
		goto _test_eof1;
case 1:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr1;
	goto tr0;
tr1:
#line 1 "NONE"
	{te = p+1;}
	goto st24;
st24:
	if ( ++p == pe )
		goto _test_eof24;
case 24:
#line 405 "parser/machine.c"
	switch( (*p) ) {
		case 69: goto st2;
		case 101: goto st2;
	}
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr1;
	goto tr68;
st2:
	if ( ++p == pe )
		goto _test_eof2;
case 2:
	switch( (*p) ) {
		case 43: goto st3;
		case 45: goto st3;
	}
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st25;
	goto tr2;
st3:
	if ( ++p == pe )
		goto _test_eof3;
case 3:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st25;
	goto tr2;
st25:
	if ( ++p == pe )
		goto _test_eof25;
case 25:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st25;
	goto tr68;
st26:
	if ( ++p == pe )
		goto _test_eof26;
case 26:
	switch( (*p) ) {
		case 9: goto st26;
		case 13: goto st26;
		case 32: goto st26;
	}
	goto tr70;
st27:
	if ( ++p == pe )
		goto _test_eof27;
case 27:
	if ( (*p) == 61 )
		goto tr71;
	goto tr66;
st28:
	if ( ++p == pe )
		goto _test_eof28;
case 28:
	switch( (*p) ) {
		case 10: goto tr72;
		case 13: goto tr72;
	}
	goto st28;
st29:
	if ( ++p == pe )
		goto _test_eof29;
case 29:
	if ( (*p) == 123 )
		goto tr73;
	goto tr66;
st30:
	if ( ++p == pe )
		goto _test_eof30;
case 30:
	if ( (*p) == 38 )
		goto tr74;
	goto tr66;
st31:
	if ( ++p == pe )
		goto _test_eof31;
case 31:
	if ( (*p) == 39 )
		goto tr75;
	goto tr66;
tr42:
#line 1 "NONE"
	{te = p+1;}
#line 98 "parser/machine.rl"
	{act = 48;}
	goto st32;
st32:
	if ( ++p == pe )
		goto _test_eof32;
case 32:
#line 492 "parser/machine.c"
	switch( (*p) ) {
		case 43: goto tr76;
		case 47: goto st5;
		case 95: goto st4;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto st4;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st4;
	} else
		goto st4;
	goto tr66;
tr9:
#line 1 "NONE"
	{te = p+1;}
#line 76 "parser/machine.rl"
	{act = 30;}
	goto st33;
tr76:
#line 1 "NONE"
	{te = p+1;}
#line 85 "parser/machine.rl"
	{act = 39;}
	goto st33;
st33:
	if ( ++p == pe )
		goto _test_eof33;
case 33:
#line 518 "parser/machine.c"
	switch( (*p) ) {
		case 43: goto st4;
		case 47: goto st5;
		case 95: goto st4;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto st4;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st4;
	} else
		goto st4;
	goto tr5;
st4:
	if ( ++p == pe )
		goto _test_eof4;
case 4:
	switch( (*p) ) {
		case 43: goto st4;
		case 47: goto st5;
		case 95: goto st4;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto st4;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st4;
	} else
		goto st4;
	goto tr5;
st5:
	if ( ++p == pe )
		goto _test_eof5;
case 5:
	switch( (*p) ) {
		case 43: goto st34;
		case 95: goto st34;
	}
	if ( (*p) < 48 ) {
		if ( 45 <= (*p) && (*p) <= 46 )
			goto st34;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st34;
		} else if ( (*p) >= 65 )
			goto st34;
	} else
		goto st34;
	goto tr5;
st34:
	if ( ++p == pe )
		goto _test_eof34;
case 34:
	switch( (*p) ) {
		case 43: goto st34;
		case 47: goto st35;
		case 95: goto st34;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto st34;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st34;
	} else
		goto st34;
	goto tr77;
st35:
	if ( ++p == pe )
		goto _test_eof35;
case 35:
	switch( (*p) ) {
		case 43: goto st34;
		case 95: goto st34;
	}
	if ( (*p) < 48 ) {
		if ( 45 <= (*p) && (*p) <= 46 )
			goto st34;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st34;
		} else if ( (*p) >= 65 )
			goto st34;
	} else
		goto st34;
	goto tr77;
tr43:
#line 1 "NONE"
	{te = p+1;}
#line 98 "parser/machine.rl"
	{act = 48;}
	goto st36;
st36:
	if ( ++p == pe )
		goto _test_eof36;
case 36:
#line 616 "parser/machine.c"
	switch( (*p) ) {
		case 43: goto st4;
		case 47: goto st5;
		case 62: goto tr79;
		case 95: goto st4;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto st4;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st4;
	} else
		goto st4;
	goto tr66;
tr44:
#line 1 "NONE"
	{te = p+1;}
#line 98 "parser/machine.rl"
	{act = 48;}
	goto st37;
st37:
	if ( ++p == pe )
		goto _test_eof37;
case 37:
#line 639 "parser/machine.c"
	switch( (*p) ) {
		case 43: goto st4;
		case 45: goto st4;
		case 46: goto st6;
		case 47: goto st5;
		case 95: goto st4;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr81;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st4;
	} else
		goto st4;
	goto tr66;
st6:
	if ( ++p == pe )
		goto _test_eof6;
case 6:
	switch( (*p) ) {
		case 43: goto st4;
		case 46: goto tr9;
		case 47: goto st5;
		case 95: goto st4;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto st4;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st4;
	} else
		goto st4;
	goto tr0;
tr81:
#line 1 "NONE"
	{te = p+1;}
#line 72 "parser/machine.rl"
	{act = 27;}
	goto st38;
st38:
	if ( ++p == pe )
		goto _test_eof38;
case 38:
#line 682 "parser/machine.c"
	switch( (*p) ) {
		case 43: goto st4;
		case 47: goto st5;
		case 69: goto st7;
		case 95: goto st4;
		case 101: goto st7;
	}
	if ( (*p) < 48 ) {
		if ( 45 <= (*p) && (*p) <= 46 )
			goto st4;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st4;
		} else if ( (*p) >= 65 )
			goto st4;
	} else
		goto tr81;
	goto tr68;
st7:
	if ( ++p == pe )
		goto _test_eof7;
case 7:
	switch( (*p) ) {
		case 43: goto st8;
		case 45: goto st8;
		case 46: goto st4;
		case 47: goto st5;
		case 95: goto st4;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr11;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st4;
	} else
		goto st4;
	goto tr2;
st8:
	if ( ++p == pe )
		goto _test_eof8;
case 8:
	switch( (*p) ) {
		case 43: goto st4;
		case 47: goto st5;
		case 95: goto st4;
	}
	if ( (*p) < 48 ) {
		if ( 45 <= (*p) && (*p) <= 46 )
			goto st4;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st4;
		} else if ( (*p) >= 65 )
			goto st4;
	} else
		goto tr11;
	goto tr2;
tr11:
#line 1 "NONE"
	{te = p+1;}
#line 72 "parser/machine.rl"
	{act = 27;}
	goto st39;
st39:
	if ( ++p == pe )
		goto _test_eof39;
case 39:
#line 750 "parser/machine.c"
	switch( (*p) ) {
		case 43: goto st4;
		case 47: goto st5;
		case 95: goto st4;
	}
	if ( (*p) < 48 ) {
		if ( 45 <= (*p) && (*p) <= 46 )
			goto st4;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st4;
		} else if ( (*p) >= 65 )
			goto st4;
	} else
		goto tr11;
	goto tr68;
tr45:
#line 1 "NONE"
	{te = p+1;}
	goto st40;
st40:
	if ( ++p == pe )
		goto _test_eof40;
case 40:
#line 774 "parser/machine.c"
	switch( (*p) ) {
		case 42: goto st9;
		case 43: goto st34;
		case 47: goto tr83;
		case 95: goto st34;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto st34;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st34;
	} else
		goto st34;
	goto tr66;
st9:
	if ( ++p == pe )
		goto _test_eof9;
case 9:
	if ( (*p) == 42 )
		goto st10;
	goto st9;
st10:
	if ( ++p == pe )
		goto _test_eof10;
case 10:
	switch( (*p) ) {
		case 42: goto st10;
		case 47: goto tr14;
	}
	goto st9;
tr46:
#line 1 "NONE"
	{te = p+1;}
#line 73 "parser/machine.rl"
	{act = 28;}
	goto st41;
st41:
	if ( ++p == pe )
		goto _test_eof41;
case 41:
#line 813 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st4;
		case 45: goto tr54;
		case 46: goto st4;
		case 47: goto st5;
		case 95: goto tr54;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr46;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr54;
	} else
		goto tr54;
	goto tr84;
st42:
	if ( ++p == pe )
		goto _test_eof42;
case 42:
	switch( (*p) ) {
		case 39: goto st42;
		case 45: goto st42;
		case 95: goto st42;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto st42;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st42;
	} else
		goto st42;
	goto tr86;
tr54:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st43;
st43:
	if ( ++p == pe )
		goto _test_eof43;
case 43:
#line 856 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st4;
		case 46: goto st4;
		case 47: goto st5;
		case 95: goto tr54;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr54;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr54;
	} else
		goto tr54;
	goto tr86;
tr47:
#line 1 "NONE"
	{te = p+1;}
#line 73 "parser/machine.rl"
	{act = 28;}
	goto st44;
st44:
	if ( ++p == pe )
		goto _test_eof44;
case 44:
#line 880 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st4;
		case 45: goto tr54;
		case 46: goto tr81;
		case 47: goto st5;
		case 95: goto tr54;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr47;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr54;
	} else
		goto tr54;
	goto tr84;
tr49:
#line 1 "NONE"
	{te = p+1;}
	goto st45;
st45:
	if ( ++p == pe )
		goto _test_eof45;
case 45:
#line 904 "parser/machine.c"
	switch( (*p) ) {
		case 43: goto st11;
		case 61: goto tr87;
		case 95: goto st11;
	}
	if ( (*p) < 48 ) {
		if ( 45 <= (*p) && (*p) <= 46 )
			goto st11;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st11;
		} else if ( (*p) >= 65 )
			goto st11;
	} else
		goto st11;
	goto tr66;
st11:
	if ( ++p == pe )
		goto _test_eof11;
case 11:
	switch( (*p) ) {
		case 43: goto st11;
		case 47: goto st12;
		case 62: goto tr17;
		case 95: goto st11;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto st11;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st11;
	} else
		goto st11;
	goto tr0;
st12:
	if ( ++p == pe )
		goto _test_eof12;
case 12:
	switch( (*p) ) {
		case 43: goto st11;
		case 95: goto st11;
	}
	if ( (*p) < 48 ) {
		if ( 45 <= (*p) && (*p) <= 46 )
			goto st11;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st11;
		} else if ( (*p) >= 65 )
			goto st11;
	} else
		goto st11;
	goto tr0;
st46:
	if ( ++p == pe )
		goto _test_eof46;
case 46:
	if ( (*p) == 61 )
		goto tr88;
	goto tr66;
st47:
	if ( ++p == pe )
		goto _test_eof47;
case 47:
	if ( (*p) == 61 )
		goto tr89;
	goto tr66;
tr52:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st48;
tr95:
#line 1 "NONE"
	{te = p+1;}
#line 53 "parser/machine.rl"
	{act = 9;}
	goto st48;
tr98:
#line 1 "NONE"
	{te = p+1;}
#line 54 "parser/machine.rl"
	{act = 10;}
	goto st48;
tr99:
#line 1 "NONE"
	{te = p+1;}
#line 55 "parser/machine.rl"
	{act = 11;}
	goto st48;
tr106:
#line 1 "NONE"
	{te = p+1;}
#line 57 "parser/machine.rl"
	{act = 13;}
	goto st48;
tr108:
#line 1 "NONE"
	{te = p+1;}
#line 58 "parser/machine.rl"
	{act = 14;}
	goto st48;
tr109:
#line 1 "NONE"
	{te = p+1;}
#line 59 "parser/machine.rl"
	{act = 15;}
	goto st48;
tr111:
#line 1 "NONE"
	{te = p+1;}
#line 60 "parser/machine.rl"
	{act = 16;}
	goto st48;
tr114:
#line 1 "NONE"
	{te = p+1;}
#line 61 "parser/machine.rl"
	{act = 17;}
	goto st48;
tr117:
#line 1 "NONE"
	{te = p+1;}
#line 62 "parser/machine.rl"
	{act = 18;}
	goto st48;
st48:
	if ( ++p == pe )
		goto _test_eof48;
case 48:
#line 1018 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr5;
st13:
	if ( ++p == pe )
		goto _test_eof13;
case 13:
	switch( (*p) ) {
		case 43: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto st4;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto st13;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st13;
	} else
		goto st13;
	goto tr5;
st14:
	if ( ++p == pe )
		goto _test_eof14;
case 14:
	switch( (*p) ) {
		case 33: goto st49;
		case 61: goto st49;
		case 95: goto st49;
		case 126: goto st49;
	}
	if ( (*p) < 42 ) {
		if ( 36 <= (*p) && (*p) <= 39 )
			goto st49;
	} else if ( (*p) > 58 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st49;
		} else if ( (*p) >= 63 )
			goto st49;
	} else
		goto st49;
	goto tr5;
st49:
	if ( ++p == pe )
		goto _test_eof49;
case 49:
	switch( (*p) ) {
		case 33: goto st49;
		case 61: goto st49;
		case 95: goto st49;
		case 126: goto st49;
	}
	if ( (*p) < 42 ) {
		if ( 36 <= (*p) && (*p) <= 39 )
			goto st49;
	} else if ( (*p) > 58 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st49;
		} else if ( (*p) >= 63 )
			goto st49;
	} else
		goto st49;
	goto tr90;
tr55:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st50;
st50:
	if ( ++p == pe )
		goto _test_eof50;
case 50:
#line 1106 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 115: goto tr91;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr91:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st51;
st51:
	if ( ++p == pe )
		goto _test_eof51;
case 51:
#line 1132 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 115: goto tr92;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr92:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st52;
st52:
	if ( ++p == pe )
		goto _test_eof52;
case 52:
#line 1158 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 101: goto tr93;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr93:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st53;
st53:
	if ( ++p == pe )
		goto _test_eof53;
case 53:
#line 1184 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 114: goto tr94;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr94:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st54;
st54:
	if ( ++p == pe )
		goto _test_eof54;
case 54:
#line 1210 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 116: goto tr95;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr56:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st55;
st55:
	if ( ++p == pe )
		goto _test_eof55;
case 55:
#line 1236 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 108: goto tr96;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr96:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st56;
st56:
	if ( ++p == pe )
		goto _test_eof56;
case 56:
#line 1262 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 115: goto tr97;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr97:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st57;
st57:
	if ( ++p == pe )
		goto _test_eof57;
case 57:
#line 1288 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 101: goto tr98;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr57:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st58;
st58:
	if ( ++p == pe )
		goto _test_eof58;
case 58:
#line 1314 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 102: goto tr99;
		case 110: goto tr100;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr100:
#line 1 "NONE"
	{te = p+1;}
#line 56 "parser/machine.rl"
	{act = 12;}
	goto st59;
st59:
	if ( ++p == pe )
		goto _test_eof59;
case 59:
#line 1341 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 104: goto tr102;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr101;
tr102:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st60;
st60:
	if ( ++p == pe )
		goto _test_eof60;
case 60:
#line 1367 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 101: goto tr103;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr103:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st61;
st61:
	if ( ++p == pe )
		goto _test_eof61;
case 61:
#line 1393 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 114: goto tr104;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr104:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st62;
st62:
	if ( ++p == pe )
		goto _test_eof62;
case 62:
#line 1419 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 105: goto tr105;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr105:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st63;
st63:
	if ( ++p == pe )
		goto _test_eof63;
case 63:
#line 1445 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 116: goto tr106;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr58:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st64;
st64:
	if ( ++p == pe )
		goto _test_eof64;
case 64:
#line 1471 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 101: goto tr107;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr107:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st65;
st65:
	if ( ++p == pe )
		goto _test_eof65;
case 65:
#line 1497 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 116: goto tr108;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr59:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st66;
st66:
	if ( ++p == pe )
		goto _test_eof66;
case 66:
#line 1523 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 114: goto tr109;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr60:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st67;
st67:
	if ( ++p == pe )
		goto _test_eof67;
case 67:
#line 1549 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 101: goto tr110;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr110:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st68;
st68:
	if ( ++p == pe )
		goto _test_eof68;
case 68:
#line 1575 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 99: goto tr111;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr61:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st69;
st69:
	if ( ++p == pe )
		goto _test_eof69;
case 69:
#line 1601 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 104: goto tr112;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr112:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st70;
st70:
	if ( ++p == pe )
		goto _test_eof70;
case 70:
#line 1627 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 101: goto tr113;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr113:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st71;
st71:
	if ( ++p == pe )
		goto _test_eof71;
case 71:
#line 1653 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 110: goto tr114;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr62:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st72;
st72:
	if ( ++p == pe )
		goto _test_eof72;
case 72:
#line 1679 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 105: goto tr115;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr115:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st73;
st73:
	if ( ++p == pe )
		goto _test_eof73;
case 73:
#line 1705 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 116: goto tr116;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
tr116:
#line 1 "NONE"
	{te = p+1;}
#line 74 "parser/machine.rl"
	{act = 29;}
	goto st74;
st74:
	if ( ++p == pe )
		goto _test_eof74;
case 74:
#line 1731 "parser/machine.c"
	switch( (*p) ) {
		case 39: goto st42;
		case 43: goto st13;
		case 46: goto st13;
		case 47: goto st5;
		case 58: goto st14;
		case 95: goto tr54;
		case 104: goto tr117;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto tr52;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr52;
	} else
		goto tr52;
	goto tr86;
st75:
	if ( ++p == pe )
		goto _test_eof75;
case 75:
	if ( (*p) == 124 )
		goto tr118;
	goto tr66;
tr65:
#line 1 "NONE"
	{te = p+1;}
	goto st76;
st76:
	if ( ++p == pe )
		goto _test_eof76;
case 76:
#line 1763 "parser/machine.c"
	if ( (*p) == 47 )
		goto st15;
	goto tr66;
st15:
	if ( ++p == pe )
		goto _test_eof15;
case 15:
	switch( (*p) ) {
		case 43: goto st77;
		case 95: goto st77;
	}
	if ( (*p) < 48 ) {
		if ( 45 <= (*p) && (*p) <= 46 )
			goto st77;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st77;
		} else if ( (*p) >= 65 )
			goto st77;
	} else
		goto st77;
	goto tr0;
st77:
	if ( ++p == pe )
		goto _test_eof77;
case 77:
	switch( (*p) ) {
		case 43: goto st77;
		case 47: goto st78;
		case 95: goto st77;
	}
	if ( (*p) < 65 ) {
		if ( 45 <= (*p) && (*p) <= 57 )
			goto st77;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st77;
	} else
		goto st77;
	goto tr120;
st78:
	if ( ++p == pe )
		goto _test_eof78;
case 78:
	switch( (*p) ) {
		case 43: goto st77;
		case 95: goto st77;
	}
	if ( (*p) < 48 ) {
		if ( 45 <= (*p) && (*p) <= 46 )
			goto st77;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st77;
		} else if ( (*p) >= 65 )
			goto st77;
	} else
		goto st77;
	goto tr120;
tr22:
#line 35 "parser/machine.rl"
	{{p = ((te))-1;}{ tok(TEXT, r); add_lines(r, ts, te); }}
	goto st79;
tr24:
#line 1 "NONE"
	{	switch( act ) {
	case 0:
	{{goto st0;}}
	break;
	case 3:
	{{p = ((te))-1;} tok(TEXT, r); add_lines(r, ts, te); }
	break;
	}
	}
	goto st79;
tr122:
#line 33 "parser/machine.rl"
	{te = p+1;{ if (!tokleave('"', r)) return 1; {cs = stack[--top];goto _again;} }}
	goto st79;
tr125:
#line 35 "parser/machine.rl"
	{te = p;p--;{ tok(TEXT, r); add_lines(r, ts, te); }}
	goto st79;
tr127:
#line 36 "parser/machine.rl"
	{te = p;p--;{ tok(TEXT, r); }}
	goto st79;
tr128:
#line 34 "parser/machine.rl"
	{te = p+1;{ tokenter(INTERP, '}', r); { /* replaced nostack-return to return non-zero error */ {stack[top++] = 79;goto st22;}} }}
	goto st79;
st79:
#line 1 "NONE"
	{ts = 0;}
#line 1 "NONE"
	{act = 0;}
	if ( ++p == pe )
		goto _test_eof79;
case 79:
#line 1 "NONE"
	{ts = p;}
#line 1857 "parser/machine.c"
	switch( (*p) ) {
		case 34: goto tr122;
		case 36: goto st81;
		case 92: goto st17;
	}
	goto tr23;
tr23:
#line 1 "NONE"
	{te = p+1;}
#line 35 "parser/machine.rl"
	{act = 3;}
	goto st80;
st80:
	if ( ++p == pe )
		goto _test_eof80;
case 80:
#line 1871 "parser/machine.c"
	switch( (*p) ) {
		case 34: goto tr125;
		case 36: goto st16;
		case 92: goto st17;
	}
	goto tr23;
st16:
	if ( ++p == pe )
		goto _test_eof16;
case 16:
	switch( (*p) ) {
		case 34: goto tr22;
		case 123: goto tr22;
	}
	goto tr23;
st17:
	if ( ++p == pe )
		goto _test_eof17;
case 17:
	goto tr23;
st81:
	if ( ++p == pe )
		goto _test_eof81;
case 81:
	switch( (*p) ) {
		case 34: goto tr127;
		case 123: goto tr128;
	}
	goto tr23;
tr25:
#line 45 "parser/machine.rl"
	{{p = ((te))-1;}{ tok(TEXT, r); add_lines(r, ts, te); }}
	goto st82;
tr29:
#line 1 "NONE"
	{	switch( act ) {
	case 5:
	{{p = ((te))-1;} if (!tokleave(II, r)) return 1; {cs = stack[--top];goto _again;} }
	break;
	case 7:
	{{p = ((te))-1;} tok(TEXT, r); add_lines(r, ts, te); }
	break;
	}
	}
	goto st82;
tr131:
#line 45 "parser/machine.rl"
	{te = p;p--;{ tok(TEXT, r); add_lines(r, ts, te); }}
	goto st82;
tr134:
#line 46 "parser/machine.rl"
	{te = p;p--;{ tok(TEXT, r); }}
	goto st82;
tr135:
#line 44 "parser/machine.rl"
	{te = p+1;{ tokenter(INTERP, '}', r); { /* replaced nostack-return to return non-zero error */ {stack[top++] = 82;goto st22;}} }}
	goto st82;
tr137:
#line 43 "parser/machine.rl"
	{te = p;p--;{ if (!tokleave(II, r)) return 1; {cs = stack[--top];goto _again;} }}
	goto st82;
st82:
#line 1 "NONE"
	{ts = 0;}
	if ( ++p == pe )
		goto _test_eof82;
case 82:
#line 1 "NONE"
	{ts = p;}
#line 1932 "parser/machine.c"
	switch( (*p) ) {
		case 36: goto st84;
		case 39: goto st85;
	}
	goto tr26;
tr26:
#line 1 "NONE"
	{te = p+1;}
#line 45 "parser/machine.rl"
	{act = 7;}
	goto st83;
st83:
	if ( ++p == pe )
		goto _test_eof83;
case 83:
#line 1945 "parser/machine.c"
	switch( (*p) ) {
		case 36: goto st18;
		case 39: goto st19;
	}
	goto tr26;
st18:
	if ( ++p == pe )
		goto _test_eof18;
case 18:
	switch( (*p) ) {
		case 39: goto tr25;
		case 123: goto tr25;
	}
	goto tr26;
st19:
	if ( ++p == pe )
		goto _test_eof19;
case 19:
	switch( (*p) ) {
		case 36: goto tr25;
		case 39: goto st20;
	}
	goto tr26;
st20:
	if ( ++p == pe )
		goto _test_eof20;
case 20:
	switch( (*p) ) {
		case 36: goto tr26;
		case 39: goto tr26;
		case 92: goto st21;
	}
	goto tr25;
st21:
	if ( ++p == pe )
		goto _test_eof21;
case 21:
	goto tr26;
st84:
	if ( ++p == pe )
		goto _test_eof84;
case 84:
	switch( (*p) ) {
		case 39: goto tr134;
		case 123: goto tr135;
	}
	goto tr26;
st85:
	if ( ++p == pe )
		goto _test_eof85;
case 85:
	switch( (*p) ) {
		case 36: goto tr134;
		case 39: goto tr136;
	}
	goto tr26;
tr136:
#line 1 "NONE"
	{te = p+1;}
#line 43 "parser/machine.rl"
	{act = 5;}
	goto st86;
st86:
	if ( ++p == pe )
		goto _test_eof86;
case 86:
#line 2009 "parser/machine.c"
	switch( (*p) ) {
		case 36: goto tr26;
		case 39: goto tr26;
		case 92: goto st21;
	}
	goto tr137;
st0:
cs = 0;
	goto _out;
	}
	_test_eof22: cs = 22; goto _test_eof; 
	_test_eof23: cs = 23; goto _test_eof; 
	_test_eof1: cs = 1; goto _test_eof; 
	_test_eof24: cs = 24; goto _test_eof; 
	_test_eof2: cs = 2; goto _test_eof; 
	_test_eof3: cs = 3; goto _test_eof; 
	_test_eof25: cs = 25; goto _test_eof; 
	_test_eof26: cs = 26; goto _test_eof; 
	_test_eof27: cs = 27; goto _test_eof; 
	_test_eof28: cs = 28; goto _test_eof; 
	_test_eof29: cs = 29; goto _test_eof; 
	_test_eof30: cs = 30; goto _test_eof; 
	_test_eof31: cs = 31; goto _test_eof; 
	_test_eof32: cs = 32; goto _test_eof; 
	_test_eof33: cs = 33; goto _test_eof; 
	_test_eof4: cs = 4; goto _test_eof; 
	_test_eof5: cs = 5; goto _test_eof; 
	_test_eof34: cs = 34; goto _test_eof; 
	_test_eof35: cs = 35; goto _test_eof; 
	_test_eof36: cs = 36; goto _test_eof; 
	_test_eof37: cs = 37; goto _test_eof; 
	_test_eof6: cs = 6; goto _test_eof; 
	_test_eof38: cs = 38; goto _test_eof; 
	_test_eof7: cs = 7; goto _test_eof; 
	_test_eof8: cs = 8; goto _test_eof; 
	_test_eof39: cs = 39; goto _test_eof; 
	_test_eof40: cs = 40; goto _test_eof; 
	_test_eof9: cs = 9; goto _test_eof; 
	_test_eof10: cs = 10; goto _test_eof; 
	_test_eof41: cs = 41; goto _test_eof; 
	_test_eof42: cs = 42; goto _test_eof; 
	_test_eof43: cs = 43; goto _test_eof; 
	_test_eof44: cs = 44; goto _test_eof; 
	_test_eof45: cs = 45; goto _test_eof; 
	_test_eof11: cs = 11; goto _test_eof; 
	_test_eof12: cs = 12; goto _test_eof; 
	_test_eof46: cs = 46; goto _test_eof; 
	_test_eof47: cs = 47; goto _test_eof; 
	_test_eof48: cs = 48; goto _test_eof; 
	_test_eof13: cs = 13; goto _test_eof; 
	_test_eof14: cs = 14; goto _test_eof; 
	_test_eof49: cs = 49; goto _test_eof; 
	_test_eof50: cs = 50; goto _test_eof; 
	_test_eof51: cs = 51; goto _test_eof; 
	_test_eof52: cs = 52; goto _test_eof; 
	_test_eof53: cs = 53; goto _test_eof; 
	_test_eof54: cs = 54; goto _test_eof; 
	_test_eof55: cs = 55; goto _test_eof; 
	_test_eof56: cs = 56; goto _test_eof; 
	_test_eof57: cs = 57; goto _test_eof; 
	_test_eof58: cs = 58; goto _test_eof; 
	_test_eof59: cs = 59; goto _test_eof; 
	_test_eof60: cs = 60; goto _test_eof; 
	_test_eof61: cs = 61; goto _test_eof; 
	_test_eof62: cs = 62; goto _test_eof; 
	_test_eof63: cs = 63; goto _test_eof; 
	_test_eof64: cs = 64; goto _test_eof; 
	_test_eof65: cs = 65; goto _test_eof; 
	_test_eof66: cs = 66; goto _test_eof; 
	_test_eof67: cs = 67; goto _test_eof; 
	_test_eof68: cs = 68; goto _test_eof; 
	_test_eof69: cs = 69; goto _test_eof; 
	_test_eof70: cs = 70; goto _test_eof; 
	_test_eof71: cs = 71; goto _test_eof; 
	_test_eof72: cs = 72; goto _test_eof; 
	_test_eof73: cs = 73; goto _test_eof; 
	_test_eof74: cs = 74; goto _test_eof; 
	_test_eof75: cs = 75; goto _test_eof; 
	_test_eof76: cs = 76; goto _test_eof; 
	_test_eof15: cs = 15; goto _test_eof; 
	_test_eof77: cs = 77; goto _test_eof; 
	_test_eof78: cs = 78; goto _test_eof; 
	_test_eof79: cs = 79; goto _test_eof; 
	_test_eof80: cs = 80; goto _test_eof; 
	_test_eof16: cs = 16; goto _test_eof; 
	_test_eof17: cs = 17; goto _test_eof; 
	_test_eof81: cs = 81; goto _test_eof; 
	_test_eof82: cs = 82; goto _test_eof; 
	_test_eof83: cs = 83; goto _test_eof; 
	_test_eof18: cs = 18; goto _test_eof; 
	_test_eof19: cs = 19; goto _test_eof; 
	_test_eof20: cs = 20; goto _test_eof; 
	_test_eof21: cs = 21; goto _test_eof; 
	_test_eof84: cs = 84; goto _test_eof; 
	_test_eof85: cs = 85; goto _test_eof; 
	_test_eof86: cs = 86; goto _test_eof; 

	_test_eof: {}
	if ( p == eof )
	{
	switch ( cs ) {
	case 23: goto tr66;
	case 1: goto tr0;
	case 24: goto tr68;
	case 2: goto tr2;
	case 3: goto tr2;
	case 25: goto tr68;
	case 26: goto tr70;
	case 27: goto tr66;
	case 28: goto tr72;
	case 29: goto tr66;
	case 30: goto tr66;
	case 31: goto tr66;
	case 32: goto tr66;
	case 33: goto tr5;
	case 4: goto tr5;
	case 5: goto tr5;
	case 34: goto tr77;
	case 35: goto tr77;
	case 36: goto tr66;
	case 37: goto tr66;
	case 6: goto tr0;
	case 38: goto tr68;
	case 7: goto tr2;
	case 8: goto tr2;
	case 39: goto tr68;
	case 40: goto tr66;
	case 9: goto tr0;
	case 10: goto tr0;
	case 41: goto tr84;
	case 42: goto tr86;
	case 43: goto tr86;
	case 44: goto tr84;
	case 45: goto tr66;
	case 11: goto tr0;
	case 12: goto tr0;
	case 46: goto tr66;
	case 47: goto tr66;
	case 48: goto tr5;
	case 13: goto tr5;
	case 14: goto tr5;
	case 49: goto tr90;
	case 50: goto tr86;
	case 51: goto tr86;
	case 52: goto tr86;
	case 53: goto tr86;
	case 54: goto tr86;
	case 55: goto tr86;
	case 56: goto tr86;
	case 57: goto tr86;
	case 58: goto tr86;
	case 59: goto tr101;
	case 60: goto tr86;
	case 61: goto tr86;
	case 62: goto tr86;
	case 63: goto tr86;
	case 64: goto tr86;
	case 65: goto tr86;
	case 66: goto tr86;
	case 67: goto tr86;
	case 68: goto tr86;
	case 69: goto tr86;
	case 70: goto tr86;
	case 71: goto tr86;
	case 72: goto tr86;
	case 73: goto tr86;
	case 74: goto tr86;
	case 75: goto tr66;
	case 76: goto tr66;
	case 15: goto tr0;
	case 77: goto tr120;
	case 78: goto tr120;
	case 80: goto tr125;
	case 16: goto tr22;
	case 17: goto tr24;
	case 81: goto tr127;
	case 83: goto tr131;
	case 18: goto tr25;
	case 19: goto tr25;
	case 20: goto tr25;
	case 21: goto tr29;
	case 84: goto tr134;
	case 85: goto tr134;
	case 86: goto tr137;
	}
	}

	_out: {}
	}

#line 151 "parser/machine.rl"

    if (p != eof) {
        set_err("precedes the token that failed to lex");
        return 1;
    } else if (backrefs_len(&backrefs) != 0) {
        /* unterminated construct */
        set_err("is not terminated");
        free(backrefs.v);
        return 1;
    }
    free(backrefs.v);
    return 0;
}
